version: "3"
services:
  pcatwHomeworkBackend:
    image: pcatwHomeworkBackend
    expose:
      - 3000
    ports:
      - 3000:3000
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379